'------------------------------------------------------------------------------
' <auto-generated>
'     Dieser Code wurde von einem Tool generiert.
'     Laufzeitversion:4.0.30319.42000
'
'     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
'     der Code erneut generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    '-Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    'Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    'mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    '''<summary>
    '''  Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Ember_Media_Manager.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        '''  Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property actor_silhouette() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("actor_silhouette", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ad() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ad", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property asc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("asc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property colRating() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("colRating", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property colUserRating() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("colUserRating", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property de() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("de", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property desc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("desc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property doRating() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("doRating", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property EmberSplashScreen() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("EmberSplashScreen", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property en() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("en", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property General() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("General", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property hasActorThumb() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hasActorThumb", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property hasBanner() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hasBanner", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property hasCharacterArt() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hasCharacterArt", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property hasClearArt() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hasClearArt", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property hasClearLogo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hasClearLogo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property hasDiscArt() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hasDiscArt", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property hasExtrafanart() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hasExtrafanart", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property hasExtrathumb() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hasExtrathumb", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property hasFanart() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hasFanart", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property hasLandscape() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hasLandscape", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property hasLanguage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hasLanguage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property hasMeta() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hasMeta", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property hasNfo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hasNfo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property hasPoster() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hasPoster", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property hasSet() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hasSet", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property hasSubtitle() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hasSubtitle", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property hasTheme() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hasTheme", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property hasTrailer() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hasTrailer", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property haswatched() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("haswatched", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property heart() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("heart", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imdb() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imdb", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property invalid() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("invalid", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
        '''&lt;Languages&gt;
        '''  &lt;Language&gt;
        '''    &lt;name&gt;Dansk&lt;/name&gt;
        '''    &lt;abbreviation&gt;da&lt;/abbreviation&gt;
        '''    &lt;id&gt;10&lt;/id&gt;
        '''  &lt;/Language&gt;
        '''  &lt;Language&gt;
        '''    &lt;name&gt;Suomeksi&lt;/name&gt;
        '''    &lt;abbreviation&gt;fi&lt;/abbreviation&gt;
        '''    &lt;id&gt;11&lt;/id&gt;
        '''  &lt;/Language&gt;
        '''  &lt;Language&gt;
        '''    &lt;name&gt;Nederlands&lt;/name&gt;
        '''    &lt;abbreviation&gt;nl&lt;/abbreviation&gt;
        '''    &lt;id&gt;13&lt;/id&gt;
        '''  &lt;/Language&gt;
        '''  &lt;Language&gt;
        '''    &lt;name&gt;Deutsch&lt;/name&gt;
        '''    &lt;abbreviation&gt;de&lt;/abbreviation&gt;
        '''    &lt;id&gt;14&lt;/id&gt;
        '''  &lt;/Language&gt;
        '''  &lt;Language&gt;
        '''    &lt;n [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        '''</summary>
        Friend ReadOnly Property languages() As String
            Get
                Return ResourceManager.GetString("languages", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Logo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Logo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die &lt;center&gt;&lt;b&gt;Movie List&lt;/b&gt;&lt;/center&gt;&lt;/br&gt; ähnelt.
        '''</summary>
        Friend ReadOnly Property MediaListLogo() As String
            Get
                Return ResourceManager.GetString("MediaListLogo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property menuAdd() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("menuAdd", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Miscellaneous() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Miscellaneous", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property modules() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("modules", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Movie() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Movie", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;!--
        '''### Anchor Help ###
        '''0 = none
        '''1 = Top
        '''2 = Bottom
        '''4 = Left
        '''8 = Right
        '''
        '''Can be combined by adding values. For example, the standard TopLeft anchor would
        '''be anchor code 5.
        '''
        '''### FontStyle Help ###
        '''0 = Regular
        '''1 = Bold
        '''2 = Italic
        '''4 = Underline
        '''8 = Strikeout
        '''
        '''Can be combined by adding values. For example, bold and underlined would be
        '''fontstyle code 5.
        '''
        '''### Color Help ###
        '''Color can be a &quot;system-defined color&quot; https://msdn.microsoft.com/en-us/library/ [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        '''</summary>
        Friend ReadOnly Property movie_Default() As String
            Get
                Return ResourceManager.GetString("movie_Default", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die 
        '''&lt;/body&gt;
        '''&lt;/html&gt; ähnelt.
        '''</summary>
        Friend ReadOnly Property MovieListFooter() As String
            Get
                Return ResourceManager.GetString("MovieListFooter", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die &lt;html&gt;
        '''&lt;head&gt;
        '''&lt;style type=&quot;text/css&quot;&gt;
        '''&lt;!--
        '''body {background: #FFFFFF; /* The background of the page will be colored white */}
        '''a:link {color: #000000; /* All unvisited links will be colored black */ }
        '''a:visited {color: #FF9900; /* All visited links will be colored tan */ }
        '''a:active {color: #FF0000; /* All active links will be colored red */}
        '''a:hover {color: #0000FF; background: #FFFF00;}
        '''/* When the mouse pointer is over the link the link will be colored blue
        '''and the background color of the link wi [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        '''</summary>
        Friend ReadOnly Property MovieListHeader() As String
            Get
                Return ResourceManager.GetString("MovieListHeader", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die &lt;td&gt;&lt;span style=&quot;color:darkblue;&quot;&gt;{0}&lt;/span&gt;&lt;/td&gt; ähnelt.
        '''</summary>
        Friend ReadOnly Property MovieListTableCol() As String
            Get
                Return ResourceManager.GetString("MovieListTableCol", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die &lt;/table&gt;
        '''&lt;/center&gt; ähnelt.
        '''</summary>
        Friend ReadOnly Property MovieListTableEnd() As String
            Get
                Return ResourceManager.GetString("MovieListTableEnd", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die &lt;th style=&quot;text-align:left; &quot;&gt;{0}&lt;/th&gt; ähnelt.
        '''</summary>
        Friend ReadOnly Property MovieListTableHeader() As String
            Get
                Return ResourceManager.GetString("MovieListTableHeader", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die &lt;/tr&gt; ähnelt.
        '''</summary>
        Friend ReadOnly Property MovieListTableRowEnd() As String
            Get
                Return ResourceManager.GetString("MovieListTableRowEnd", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die 
        '''&lt;tr&gt; ähnelt.
        '''</summary>
        Friend ReadOnly Property MovieListTableRowStart() As String
            Get
                Return ResourceManager.GetString("MovieListTableRowStart", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die &lt;center&gt;
        '''&lt;table class=&quot;emm_table&quot;&gt;
        ''' ähnelt.
        '''</summary>
        Friend ReadOnly Property MovieListTableStart() As String
            Get
                Return ResourceManager.GetString("MovieListTableStart", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MovieSet() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MovieSet", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;!--
        '''### Anchor Help ###
        '''0 = none
        '''1 = Top
        '''2 = Bottom
        '''4 = Left
        '''8 = Right
        '''
        '''Can be combined by adding values. For example, the standard TopLeft anchor would
        '''be anchor code 5.
        '''
        '''### FontStyle Help ###
        '''0 = Regular
        '''1 = Bold
        '''2 = Italic
        '''4 = Underline
        '''8 = Strikeout
        '''
        '''Can be combined by adding values. For example, bold and underlined would be
        '''fontstyle code 5.
        '''
        '''### Color Help ###
        '''Color can be a &quot;system-defined color&quot; https://msdn.microsoft.com/en-us/library/ [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        '''</summary>
        Friend ReadOnly Property movieset_Default() As String
            Get
                Return ResourceManager.GetString("movieset_Default", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property msaa() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("msaa", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property noposter() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("noposter", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Play_Icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Play_Icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property preview() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("preview", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property puzzle() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("puzzle", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property star() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("star", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property starempty() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("starempty", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property starhalf() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("starhalf", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property tmdb() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tmdb", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property tvdb() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tvdb", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;!--
        '''### Anchor Help ###
        '''0 = none
        '''1 = Top
        '''2 = Bottom
        '''4 = Left
        '''8 = Right
        '''
        '''Can be combined by adding values. For example, the standard TopLeft anchor would
        '''be anchor code 5.
        '''
        '''### FontStyle Help ###
        '''0 = Regular
        '''1 = Bold
        '''2 = Italic
        '''4 = Underline
        '''8 = Strikeout
        '''
        '''Can be combined by adding values. For example, bold and underlined would be
        '''fontstyle code 5.
        '''
        '''### Color Help ###
        '''Color can be a &quot;system-defined color&quot; https://msdn.microsoft.com/en-us/library/ [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        '''</summary>
        Friend ReadOnly Property tvep_Default() As String
            Get
                Return ResourceManager.GetString("tvep_Default", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;!--
        '''### Anchor Help ###
        '''0 = none
        '''1 = Top
        '''2 = Bottom
        '''4 = Left
        '''8 = Right
        '''
        '''Can be combined by adding values. For example, the standard TopLeft anchor would
        '''be anchor code 5.
        '''
        '''### FontStyle Help ###
        '''0 = Regular
        '''1 = Bold
        '''2 = Italic
        '''4 = Underline
        '''8 = Strikeout
        '''
        '''Can be combined by adding values. For example, bold and underlined would be
        '''fontstyle code 5.
        '''
        '''### Color Help ###
        '''Color can be a &quot;system-defined color&quot; https://msdn.microsoft.com/en-us/library/ [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        '''</summary>
        Friend ReadOnly Property tvshow_Default() As String
            Get
                Return ResourceManager.GetString("tvshow_Default", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TVShows() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TVShows", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property tvtunes() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tvtunes", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property undo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("undo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die http://www.EmberMediaManager.org/ ähnelt.
        '''</summary>
        Friend ReadOnly Property urlEmberMediaManager() As String
            Get
                Return ResourceManager.GetString("urlEmberMediaManager", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die http://wiki.embermediamanager.org ähnelt.
        '''</summary>
        Friend ReadOnly Property urlEmberWiki() As String
            Get
                Return ResourceManager.GetString("urlEmberWiki", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die http://www.ffmpeg.org/ ähnelt.
        '''</summary>
        Friend ReadOnly Property urlFfmpeg() As String
            Get
                Return ResourceManager.GetString("urlFfmpeg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die http://forum.kodi.tv/forumdisplay.php?fid=195 ähnelt.
        '''</summary>
        Friend ReadOnly Property urlForumEng() As String
            Get
                Return ResourceManager.GetString("urlForumEng", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die http://www.kodinerds.net/index.php/Board/105-Ember-Media-Manager/ ähnelt.
        '''</summary>
        Friend ReadOnly Property urlForumGer() As String
            Get
                Return ResourceManager.GetString("urlForumGer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die http://www.imdb.com/ ähnelt.
        '''</summary>
        Friend ReadOnly Property urlIMDB() As String
            Get
                Return ResourceManager.GetString("urlIMDB", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die http://www.impawards.com/ ähnelt.
        '''</summary>
        Friend ReadOnly Property urlIMPAwards() As String
            Get
                Return ResourceManager.GetString("urlIMPAwards", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die http://mediainfo.sourceforge.net ähnelt.
        '''</summary>
        Friend ReadOnly Property urlMediaInfo() As String
            Get
                Return ResourceManager.GetString("urlMediaInfo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die http://www.moviepostersdb.com/ ähnelt.
        '''</summary>
        Friend ReadOnly Property urlMoviePostersDb() As String
            Get
                Return ResourceManager.GetString("urlMoviePostersDb", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die http://forum.kodi.tv/showthread.php?tid=259449 ähnelt.
        '''</summary>
        Friend ReadOnly Property urlReleaseThread() As String
            Get
                Return ResourceManager.GetString("urlReleaseThread", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die http://www.themoviedb.org/ ähnelt.
        '''</summary>
        Friend ReadOnly Property urlTheMovieDb() As String
            Get
                Return ResourceManager.GetString("urlTheMovieDb", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die http://thetvdb.com/ ähnelt.
        '''</summary>
        Friend ReadOnly Property urlTVDB() As String
            Get
                Return ResourceManager.GetString("urlTVDB", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die http://www.xbmc.org/ ähnelt.
        '''</summary>
        Friend ReadOnly Property urlXBMC() As String
            Get
                Return ResourceManager.GetString("urlXBMC", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die http://www.youtube.com/ ähnelt.
        '''</summary>
        Friend ReadOnly Property urlYouTube() As String
            Get
                Return ResourceManager.GetString("urlYouTube", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property valid() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("valid", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property valid2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("valid2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Wizard() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Wizard", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
